# Generated by Django 4.2.5 on 2025-07-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
