# Generated by Django 5.2.4 on 2025-07-22 00:46

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_card',
            field=models.FileField(blank=True, null=True, upload_to='business_cards/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='share_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
