# Generated by Django 5.2.4 on 2025-07-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_business_card_profile_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
