# Generated by Django 5.2.4 on 2025-07-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_profile_qr_code_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_congrats',
            field=models.BooleanField(default=False),
        ),
    ]
