# Generated by Django 5.2.4 on 2025-07-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_has_seen_congrats'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
