# Generated by Django 4.2.5 on 2025-08-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='metier',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='metier_hero_images/'),
        ),
    ]
