# Generated by Django 4.2.5 on 2025-08-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_metier_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='template',
            field=models.CharField(choices=[('classic', 'Classique (Bois)'), ('modern', 'Moderne'), ('minimal', 'Minimaliste'), ('elegant', 'Élégant')], default='classic', max_length=20),
        ),
    ]
