# Generated by Django 4.2.5 on 2025-08-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_dashboard_tour',
            field=models.BooleanField(default=False),
        ),
    ]
