# Generated by Django 4.2.5 on 2025-08-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profile_has_seen_dashboard_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_seen_dashboard_tour',
        ),
    ]
