# Generated by Django 4.2.5 on 2025-08-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_profile_has_seen_dashboard_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_dashboard_tour',
            field=models.BooleanField(default=False),
        ),
    ]
